version: '3.8'

services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/app
    ports:
      - "1000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "1001:3306"
